FROM node:12.18.1-alpine3.12

RUN apk update && apk add --update --no-cache bash git py-pip make g++

ARG APP_DIR=/home/node/graphichat

RUN mkdir -p ${APP_DIR}/server && chown -R node:node ${APP_DIR}

WORKDIR ${APP_DIR}

COPY --chown=node:node ./.env ./
COPY --chown=node:node ./.browserslistrc ./

WORKDIR ${APP_DIR}/server

COPY ./server/package.json ./
COPY ./server/yarn.lock ./

USER node

RUN yarn install

COPY --chown=node:node ./server/. ./
