import {
  DateTimeResolver,
  NonPositiveIntResolver,
  PositiveIntResolver,
  NonNegativeIntResolver,
  NegativeIntResolver,
  NonPositiveFloatResolver,
  PositiveFloatResolver,
  NonNegativeFloatResolver,
  NegativeFloatResolver,
  EmailAddressResolver,
  URLResolver,
  PhoneNumberResolver,
  PostalCodeResolver,
} from 'graphql-scalars';

export default {
  DateTime: DateTimeResolver,
  NonPositiveInt: NonPositiveIntResolver,
  PositiveInt: PositiveIntResolver,
  NonNegativeInt: NonNegativeIntResolver,
  NegativeInt: NegativeIntResolver,
  NonPositiveFloat: NonPositiveFloatResolver,
  PositiveFloat: PositiveFloatResolver,
  NonNegativeFloat: NonNegativeFloatResolver,
  NegativeFloat: NegativeFloatResolver,
  EmailAddress: EmailAddressResolver,
  URL: URLResolver,
  PhoneNumber: PhoneNumberResolver,
  PostalCode: PostalCodeResolver,
};
